const categories = [
  "Image Recognition",
  "Dataset Of Datasets",
  "Language",
  "Performing Arts",
  "Visual Arts & Design",
  "Philosophy",
  "History",
  "Theology",
  "Anthropology & Archeology",
  "Sociology",
  "Psychology",
  "Politics",
  "Interdisciplinary",
  "Economics & Finance",
  "Demography",
  "Biology",
  "Chemistry",
  "Physics & Energy",
  "Earth & Climate",
  "Space & Astronomy",
  "Mathematics",
  "Computer Technology",
  "Engineering",
  "Agriculture & Bio Engineering",
  "Transportation",
  "Urban Planning",
  "Health & Medicine",
  "Business & Management",
  "Sports & Recreation",
  "Communication & Journalism",
  "Deep Learning",
  "Law",
  "Other"
]

export default categories